media:
  input: images
  output: /images

content:
  - name: homepage
    label: "Homepage Content"
    type: file
    path: "index.html"
    fields:
      - name: body
        label: "HTML Code"
        type: code